#!/usr/bin/env node
/**
 * build-js.js — compiles the JSX sources into one plain-JS bundle so the
 * production site ships WITHOUT Babel standalone (a ~3 MB download and an
 * in-browser compile on every visit).
 *
 *   node scripts/build-js.js         → writes public/js/build/app.bundle.js
 *
 * Run this after editing any .jsx file, then commit the bundle. For live
 * development without a build step, open index-dev.html instead — it loads
 * the raw .jsx files through Babel standalone exactly like the prototype.
 *
 * Uses the vendored public/vendor/babel.min.js (UMD works in Node), so no
 * npm install is required.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const pub = path.join(__dirname, "..", "public");
const Babel = require(path.join(pub, "vendor", "babel.min.js"));

/* Load order matters: shared UI first, app root last (same order as the
   <script type="text/babel"> tags in index-dev.html). */
const FILES = [
  "ui.jsx",
  "map.jsx",
  "directory.jsx",
  "dioceses.jsx",
  "church.jsx",
  "suggest.jsx",
  "admin-form.jsx",
  "admin-import.jsx",
  "admin-autofill.jsx",
  "admin-settings.jsx",
  "admin-suggestions.jsx",
  "admin-login.jsx",
  "admin.jsx",
  "app.jsx",
];

let bundle = "/* app.bundle.js — GENERATED by scripts/build-js.js; do not edit.\n" +
             "   Sources: public/js/*.jsx */\n";

for (const f of FILES) {
  const src = fs.readFileSync(path.join(pub, "js", f), "utf8");
  const out = Babel.transform(src, {
    presets: [["react", {}]],
    sourceType: "script",   // keep top-level consts/functions page-global, like <script> tags
    filename: f,
  }).code;
  // IIFE per file so top-level names (helpers, components) can't collide
  bundle += `\n/* ======== ${f} ======== */\n;(function () {\n${out}\n})();\n`;
}

const outDir = path.join(pub, "js", "build");
fs.mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, "app.bundle.js");
fs.writeFileSync(outFile, bundle);
console.log(`Wrote ${(bundle.length / 1024).toFixed(0)} KB to ${path.relative(process.cwd(), outFile)} (${FILES.length} modules)`);
